# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the lint rules recommended by the Flutter team.
# You can see the list of rules here:
# https://flutter.dev/docs/development/tools/linter#recommended-lints
#
# For a full list of available rules, see
# https://dart-lang.github.io/linter/lints/options/options.html

include: package:flutter_lints/flutter.yaml

linter:
  # You can customize the lint rules applied to this project in this file.
  rules:
    # prefer_single_quotes: true  # Uncomment to enable a sample rule.
