name: sencours_math
description: "Application mobile d’apprentissage des mathématiques pour le lycée au Sénégal."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gestion d'état
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.1.0

  # Rendu des formules mathématiques (LaTeX)
  flutter_math_fork: ^0.7.2

  # Stockage local (pour les progrès futurs)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Préférences utilisateur (ex: thème, classe)
  shared_preferences: ^2.2.3

  # Polices de caractères
  google_fonts: ^6.2.1

  # Animations
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
